global
  #debug                                   # uncomment to enable debug mode for HAProxy

defaults
  mode http                                # enable http mode which gives of layer 7 filtering
  timeout connect 5000ms                   # max time to wait for a connection attempt to a server to succeed
  timeout client 50000ms                   # max inactivity time on the client side
  timeout server 50000ms                   # max inactivity time on the server side

backend legacy                             # define a group of backend servers to handle legacy requests
  server legacy_server 127.0.0.1:8001      # add a server to this backend

frontend app *:80                          # define what port to listed to for HAProxy
  default_backend legacy                   # set the default server for all request
